spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: keycloak
          uri: http://${AUTHENTICATION_BASE_KEYCLOAK_SERVICE_NAME:authentication}:8080
          predicates:
            - Path=/keycloak/**

        - id: authentication-backend
          uri: http://${AUTHENTICATION_BACKEND_SERVICE_NAME:authentication-backend}:8081
          predicates:
            - Path=/auth-backend/**
          filters:
            - StripPrefix=1

        - id: authentication-frontend
          uri: http://${AUTHENTICATION_FRONTEND_SERVICE_NAME:authentication-frontend}:8080
          predicates:
            - Path=/auth/**

        - id: core-backend
          uri: http://${CORE_BACKEND_API_SERVICE_NAME:core-backend}:8080
          predicates:
            - Path=/cardpgbackend/**
          filters:
            - StripPrefix=1

        - id: calculation-engine
          uri: http://${CALCULATION_ENGINE_API_SERVICE_NAME:geo-calculation-engine-app}:8080
          predicates:
            - Path=/calculation-engine/**
          filters:
            - StripPrefix=1

        - id: geoserver
          uri: http://${GEOSERVER_SERVICE_NAME:geoserver}:8080
          predicates:
            - Path=/geoserver/**

        - id: actuator
          uri: http://localhost:8080
          predicates:
            - Path=/actuator/**

        - id: core-frontend
          uri: http://${CORE_FRONTEND_SERVICE_NAME:core-frontend}:8080
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.cloud.gateway: INFO
